# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: test hosting

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: 6.x

- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    msbuildArguments: '/t:restore;rebuild;publish /p:DeployOnBuild=True /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:SelfContained=true /p:Platform="Any CPU" /p:Configuration=Release /p:RuntimeIdentifier=win-x64'
    msbuildVersion: latest

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    arguments: -c Release --runtime win-x64 /p:PublishSingleFile=true --self-contained --output $(Build.ArtifactStagingDirectory) --no-dependencies
    projects: $(Build.SourcesDirectory)\ImmoGlobal\ImmoGlobal.csproj
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'publish'
    publishLocation: 'Container'