trigger: none
  
pool:
  name: test hosting
  demands: latex -equals true

steps:  
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'rubber --pdf main.tex'
    workingDirectory: '$(Build.SourcesDirectory)/docs'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/docs/main.pdf'
    ArtifactName: 'drop'
    publishLocation: 'Container'