@startuml mieterAnsehen
!theme cerulean-outline

skinparam sequence {
LifeLineBackgroundColor #8ECBF1
ParticipantPadding 2
}
skinparam dpi 300

actor User as user
activate user
participant Renter as renter
database Database as db
activate db
activate renter
user -> renter : load()
renter -> db : getAllRentersFromDb()
db --> renter : returnRenters()
user -> renter : selectRenter()

renter -> db : getRentalContractsToRenterFromDb()
db --> renter : returnRentalContracts()
renter -> db : getInvoicesToRenterFromDb()
db --> renter : returnInvoices()

user -> renter : editSelectedRenter()
renter ->renter : updateValuesForRenter()  
renter ->db : update()
@enduml