@startuml mietvertrag
!theme cerulean-outline
skinparam sequence {
LifeLineBackgroundColor #8ECBF1
ParticipantPadding 2
}
skinparam dpi 300

actor User as user
activate user
participant RentalContract as rc
database Database as db
activate db
create rc
user -> rc ++ : create()
rc -> db : getPropertiesFromDb()
db --> rc : retunrProperties()
user -> rc : selectProperty()
rc -> db: getPropertyObjectsToSelectedPropertyFromDb()
alt#Gold #LightBlue PropertyObjects != null && !allInUse
  db --> rc: returnPropertyObjects()
else #Pink PropertyObjects == null or allInUse
end

rc -> db : getPersonasFromDb()
alt#Gold #LightBlue persona != null
  db--> rc : returnPersonas()
else #Pink persona == null
end
user -> rc : saveValuesForRentalContract()
rc -> db : saveDb()
@enduml