@startuml mietvertragEditieren
!theme cerulean-outline
skinparam sequence {
LifeLineBackgroundColor #8ECBF1
ParticipantPadding 2
}
skinparam dpi 300

actor User as user
activate user
participant RentalContract as rc
database Database as db
activate db
activate rc

user -> rc : loadSelectedRentalContract()
rc -> db : getPersonasFromDb()
alt#Gold #LightBlue persona != null
  db--> rc : returnPersonas()
else #Pink persona == null
end

rc -> db : getPropertiesFromDb()
alt#Gold #LightBlue
  db --> rc : returnProperties()
else #Pink properties == null
end
rc -> db : getPersonaToRentalContract()
db --> rc : returnPersonaToRentalContract()
rc -> db : getPropertyObjectToRentalContract()
db --> rc : returnPropertyObjectToRentalContract()
rc -> db : getPropertyToPropertyObject()
db --> rc : returnPropertyToPropertyObject()
user -> rc : changeProperty()
rc -> db: getPropertyObjectsToSelectedPropertyFromDb()
alt#Gold #LightBlue PropertyObjects != null && !allInUse
  db --> rc: returnPropertyObjects()
else #Pink PropertyObjects == null or allInUse
end

rc -> rc : getRenter()
rc -> rc : getPropertyObjectToRentalContract()

user -> rc : saveUpdateRentalContract()
rc -> db : saveDb()
@enduml