@startuml objektAnsehenBearbeiten
!theme cerulean-outline

skinparam sequence {
LifeLineBackgroundColor #8ECBF1
ParticipantPadding 2
}
skinparam dpi 300

actor User as user
activate user
participant PropertyObject as probj
database Database as db
activate db
activate probj
user -> probj : loadSelectetPropertyObject()
probj -> db : getPropertyObject(id)
db --> probj : returnPropertyObject()
probj -> db : getRentalContractsToObjectFromDb()
alt#Gold #LightBlue rentalContractsToObject != null
db --> probj : returnRentalContractsToObject()
else #Pink rentalContractsToObject == null
end 
probj -> db : getInvoicePositionsToObjectFromDb()
alt#Gold #LightBlue invoicePositionsToObject != null
db --> probj : returnInvoicePositionsToObject()
else #Pink invoicePositionsToObject == null
end 
alt#Gold #LightBlue Edit PropertyObject
user -> probj : edit()
user ->probj : saveUpdateValuesPropertyObject()  
probj ->db : updateDb()
else #Pink delete PropertyObject
user -> probj : delete()
probj ->db : deletePropertyObjectDb()
end 
@enduml
