@startuml RechnungErstellen
!theme cerulean-outline

skinparam sequence {
LifeLineBackgroundColor #8ECBF1
ParticipantPadding 2
}
skinparam dpi 300

actor User as user
activate user
participant Invoice as inv
participant InvoicePosition as invp
database Database as db
activate db
create inv
user -> inv ++: create()
inv -> db : getPersonasFromDb()
db --> inv :returnPersonas()
user -> inv : setValuesForInvoice()
create invp
loop#Gold #LightBlue InvoicePosition
  user -> invp ++ : add()
  invp -> db : getPropertiesFromDb()
  db --> invp :returnProperties()
  invp -> db : getAccountsFromDb()
  db --> invp :returnAccounts()
  user -> invp :selectProperty()
  invp -> db : getPropertyObjectsToPropertyFromDb()
  db --> invp :returnPropertyObjectsToProperty()
  user -> invp : setValuesForInvoicePosition()
end
user -> inv : save()
inv -> db : saveInvoiceDb()

loop#Gold #LightBlue ForEachInvoicePosition
  inv -> invp : getInvoicePositionData()
  invp --> inv : returnInvoicePositionData()
  inv -> db : saveInvoicePositionDb()
end
@enduml