@startmindmap GuiMindMap
!theme cerulean-outline
skinparam dpi 300
* Liegenschaft
** neue Liegenschaft
** Objekte
*** neues Objekt
*** Mieter
*** Mietverträge
**** Mahnung erstellen
**** Rechnungen
** Hauswartungsperson

* Kreditoren
** neuer Kreditor
** Rechnungen
*** Mahnung erstellen

* Mieter
** Rechnungen
*** neue Rechnung
** Objekte
** Mietverträge
*** neuer Mietvertrag
** neuer Mieter

* Rechnungen
** neue Rechnung
* Konto
** Zahlung verbuchen
** neues Konto
@endmindmap