@startuml kontoErstellen
!theme cerulean-outline
skinparam dpi 300
left to right direction
actor "User" as fc
rectangle "Konto erstellen" {
  usecase "neues Konto erstellen" as UC1
  usecase "Kontobezeichnung eingeben" as UC2
  usecase "Kontonummer eingeben" as UC3
}  
fc -- UC1
fc -- UC2
fc -- UC3
@enduml