@startuml Kreditor erfassen
!theme cerulean-outline
skinparam dpi 300
left to right direction
actor "User" as user
rectangle "Kreditor erfassen" {
  usecase "Name eingeben" as UC1
  usecase "Adresse eingeben" as UC2
  usecase "Mehrwertsteuernummer \n eingeben" as UC3
  usecase "Telefonnummer eingeben" as UC4
  usecase "Kontakpersonendaten \n eingeben" as UC5
} 
user -- UC1
user -- UC2
user -- UC3
user -- UC4
user -- UC5
@enduml