@startuml Login
!theme cerulean-outline
actor "User" as fc
rectangle Login {
  usecase "Login" as UC1
  usecase "Verifizieren der\n Login Credentials" as UC2
}
fc -- UC1
UC1 .> UC2 : <<include>>
@enduml
