@startuml MahnungErstellen
!theme cerulean-outline

left to right direction
actor "User" as fc
rectangle "Mahnung erstellen" {
  usecase "Mahnung für den \nMieter erstellen" as UC1
  usecase "betreffenden Mieter \nauswählen"as inc1

} 
fc -- UC1
UC1 .left.> inc1 : <<include>>
@enduml