@startuml MahnungErstellen
!theme cerulean-outline
skinparam dpi 300
left to right direction
actor "User" as fc
rectangle "Mahnung erstellen" {
  usecase "Mahnung für den \nMieter/Kreditor erstellen" as UC1
  usecase "betreffenden Mieter/Kreditor \nauswählen"as inc1

} 
fc -- UC1
UC1 .left.> inc1 : <<include>>
@enduml