@startuml MahnungErstellen
!theme cerulean-outline
skinparam dpi 300
left to right direction
actor "User" as user
rectangle "Mahnung erstellen" {
  usecase "betreffenden Rechnung auswählen"as UC1
  usecase "Mahnungsbetrag eingeben" as UC2

} 
user -- UC1
user -- UC2

@enduml