@startuml MietzinsKontrollieren
!theme cerulean-outline

left to right direction
actor "User" as fc
rectangle "Mietzinskontrolle" {
  usecase "Mietzinskontrolle" as UC1
  usecase "betreffendes Objekt\n auswählen"as inc1

} 
fc -- UC1
UC1 .left.> inc1 : <<include>>
@enduml