@startuml Mieter erfassen
!theme cerulean-outline
skinparam dpi 300
left to right direction
actor "User" as user
rectangle "Mieter erfassen" {
  usecase "Name/Vorname eingeben" as UC1
  usecase "Geburtsdatum eingeben" as UC2
  usecase "Heimatort eingeben" as UC3
  usecase "Zivilstand eingeben" as UC4
  usecase "vorherige \n Adresse eingeben" as UC5
  usecase "Telefonnummer eingeben" as UC6
  usecase "Email-Adresse Privat \n & Beruflich eingeben" as UC7
  usecase "Bankverbindung eingeben" as UC8
} 
user -- UC1
user -- UC2
user -- UC3
user -- UC4
user -- UC5
user -- UC6
user -- UC7
user -- UC8
@enduml