@startuml MietzinsKontrollieren
!theme cerulean-outline
skinparam dpi 300
left to right direction
actor "User" as user
rectangle "Mietzinskontrolle" {
  usecase "Mietzinskontrolle" as UC1
  usecase "betreffendes Objekt\n auswählen"as inc1

} 
user -- UC1
UC1 .left.> inc1 : <<include>>
@enduml