@startuml MietverträgeVerwalten
!theme cerulean-outline
skinparam dpi 300
left to right direction
actor "User" as user
rectangle "Mietverträge verwalten" {
  usecase "Mietbeginn angeben" as UC1
  usecase "Neuer Mietvertrag\n erfassen" as UC2
  usecase "erfasste Objekte" as inc1
  usecase "Monatlicher Mietzins\n angeben" as UC3
  usecase "Nebenkostenart \n angeben" as UC4
  usecase "Auflistung der \n Kostenarten angeben" as UC5
  usecase "Mietdepot angeben" as UC6

} 
user -- UC1
user -- UC2
UC2 .left.> inc1 : <<include>>
user -- UC3 
user -- UC4
user -- UC5
user -- UC6
@enduml