@startuml ZahlungseingangaufKontoverbuchen
!theme cerulean-outline
skinparam dpi 300
left to right direction
actor "User" as fc
rectangle "Zahlungsein- und Ausgang \nauf Konto verbuchen" {
  usecase "Konto zum verbuchen \n auswählen" as UC1
  usecase "Auswahl der \nvorhandenen Konten" as inc1
} 
fc -- UC1
UC1 .left.> inc1 : <<include>>
@enduml