@startuml Zahlungsengang auf Konto verbuchen
!theme cerulean-outline

left to right direction
actor "User" as fc
rectangle "Zahlungsengang auf Konto verbuchen" {
  usecase "Konto zum verbuchen \n auswählen" as UC1
  usecase "Auswahl der \nvorhandenen Konten" as inc1
} 
fc -- UC1
UC1 .left.> inc1 : <<include>>
@enduml