@startuml mietvertrag

hide empty description
[*] --> Mietvertrag : neuer Mietvertrag
Mietvertrag --> ungültig
ungültig --> unterschrieben
unterschrieben --> gültig
gültig --> gekündet
gekündet --> ungültig_
ungültig_ --> [*]
@enduml